# 1. COMECE PELA IMAGEM OFICIAL PRONTA (A VERSÃO CORRETA DO README)
FROM cr.weaviate.io/semitechnologies/weaviate:1.32.2

# 2. DEFINA AS VARIÁVEIS DE AMBIENTE PADRÃO
ENV AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED='true'
ENV DEFAULT_VECTORIZER_MODULE='none'
ENV ENABLE_MODULES=''
ENV PERSISTENCE_DATA_PATH='/data'

# 3. EXPOR AS PORTAS
EXPOSE 8080
EXPOSE 50051
